
os:
  - linux
  - osx

# Supported versions: https://docs.travis-ci.com/user/languages/objective-c/#Supported-Xcode-versions
osx_image: xcode6.4

language: c
sudo: required

services:
  - docker

env:
  global:
    # Select which CUDA version to use
    - CUDA_VERSION=7.5
    - CUDA_SHORT_VERSION=75

# The Dockerfile that defines the image that for the build environment is
# available in this repo at devtools/centos5-build-box/Dockerfile
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull jchodera/omnia-build-box:cuda${CUDA_SHORT_VERSION}-amd30;
    fi

script:
  # Retrieve conda-build-all
  - wget -O conda-build-all --quiet https://raw.githubusercontent.com/omnia-md/conda-recipes/master/conda-build-all
  - chmod u+x conda-build-all
  # Select upload destination
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
        export UPLOAD="--upload omnia --dev --force";
    else
        export UPLOAD="--dev --force";
    fi
  - echo $UPLOAD

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then

        docker run -e UPLOAD -e BINSTAR_TOKEN -e TRAVIS_PULL_REQUEST
            -t -i --rm -v `pwd`:/io jchodera/omnia-build-box:cuda${CUDA_SHORT_VERSION}-amd30
            bash /io/devtools/docker-build.sh;

    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        echo "Building osx...";
        bash devtools/osx-build.sh;
    fi
