os:
  - linux
  - osx

language: c
sudo: required

services:
  - docker

env:
  global:
    secure: "FJIkUm66d96GPtgISVFewtJpSr809sjZU1AdJx15csBkxDXvzG0oi6ksTvlbOD1gqUHWeSW8K3QMklsbrtn4T+UOc0hFgq5vNKCDhXouWuSW1hzqb15o7rZ0szg4noG9JLKsZfRHsCJ37C9OHmS40kuDAadql5g/Y+Q2+6uufDX3GT+v88oIOdYHGzOEbP6juz8C/CipbEFgz5sYepB/sdovaJQkzdSV4B/A7UGbnTXmNyf7diCpQNyweaeNaxOGtVaUsK7xJfI5sjzN00a11gqLVsi6TCYc+3md7At76yvhbphCedJlDWcf/Fm9n+3xkzkZv+7btjMJGdxkHMD7iuoclw+pRURTDlCI0WJikIkP+q5fyVyzHBnRq4yz7sTqCWnS9PQRXqfRzAlM/uHxEOYciPl2MaxEhZC5i3ti7Hn8LQGTEldDj34Hq3J0oEuGj6qrihVhv703ODLdHx910Y+5QRIXWTmtR/Ze3E+xDh648V0P1B2Rmgs8KmNc3pxW+Q/QsYnXQEGfI1k2Iv/RjemMjgEHMgsjZqJyo+2K/JuKhOi/EaEU4AtV3XNrZAO+ksxBcG4TR5iK6bmqxgZ4hPoKR8vtMeY6finZOECp52PhI3NX3Ug2a5h34CnaHF0ikDHu0snbBzNueZy9bDGZhxy47kBZqxOfo8thBwl8+Pc="

# The Dockerfile that defines the image that for the build environment is
# available in this repo at devtools/centos5-build-box/Dockerfile
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull rmcgibbo/centos5-build-box;
    fi

script:
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
        export UPLOAD="--upload omnia";
    else
        export UPLOAD=" ";
    fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then

        docker run -e UPLOAD -e BINSTAR_TOKEN -e TRAVIS_PULL_REQUEST
            -t -i --rm -v `pwd`:/io rmcgibbo/centos5-build-box:latest
            bash /io/devtools/docker-build.sh;

    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then

        curl -s -O https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
        bash Miniconda3-latest-MacOSX-x86_64.sh -b -p $HOME/anaconda;
        export PATH=$HOME/anaconda/bin:$PATH;
        conda config --add channels omnia;
        conda install -yq conda-build jinja2 anaconda-client;


        if ! ./conda-build-all --check-against omnia --dry-run openmm-dev; then
            brew install -y doxygen;
            curl -O -s http://developer.download.nvidia.com/compute/cuda/7_0/Prod/network_installers/mac/cuda_mac_installer_tk.tar.gz ;
            curl -O -s http://developer.download.nvidia.com/compute/cuda/7_0/Prod/network_installers/mac/cuda_mac_installer_drv.tar.gz ;
            sudo tar -zxf cuda_mac_installer_tk.tar.gz -C /;
            sudo tar -zxf cuda_mac_installer_drv.tar.gz -C /;
        fi;

        if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
          ./conda-build-all --check-against omnia $UPLOAD * || true;
        else
          ./conda-build-all --check-against omnia $UPLOAD *;
        fi;
    fi
