os:
  - linux
  - osx

# Supported versions: https://docs.travis-ci.com/user/languages/objective-c/#Supported-Xcode-versions
osx_image: xcode6.4

language: c
sudo: required

services:
  - docker

env:
  matrix:
    - PY_BUILD_VERSION=27
    - PY_BUILD_VERSION=34
    - PY_BUILD_VERSION=35
    - PY_BUILD_VERSION=36
  global:
    - CUDA_VERSION: "8.0"
    - CUDA_SHORT_VERSION: "80"
  secure:
    - "odbGFMU2J22MBWPcw3VR1NY0FjmEYcflESRtM6mR8IlHNUa3x3wPel+jCVh2NHETe4lOP7kcOp7znMGqt4M50Z3TMkjba61hMDLc4O3zZOiisIMqCkMBHjzppTPGeJu1frdQEj8ZYFuQGxdo/mPLLr76KsqMRXUFw7df+AMbt9HCsQM3oB/KqsBW5UffbYVzmALL3SkR+vRthmRs/8ZuRZ50sKKlZ7In0iggzTKXFHArHU4aIwWod4uVeQJBhlCwetXzIWyPS819EoQ20O1HdrVJDL/NJf1tJWSpn58DC0PJL8W8L7q9D9dnAfGQe06jXYr8AUizCYUhFEdt8hTlB//dHdhJA/DzkI7ENoE/g6pLYC/sX8ZePKz9kEris1wOnWnNK6bogsqtVJZt8WcGOTp3P3RTJVJs+HPdlHCWHkBZ5QxKONVanhVZCQJ936+SHirJdFxVpHsFpMB7O7EJooKtf3quK5mhIg1z9G0DVsp9G/MGVUXQ5MWdrUg4Q3sMFBlc+27S+nxGmevcr9cgsSNGVKLE6yW/pG1OFXXuXU2i6o4yHXYQr78GwqxZ5qRVu2OR3aHNDnlLQbM6zgGIY2iIdzE86XH0zU+B8z+0XPqp7qOnaz7auvJcfWZ2uG322ej2GhZCXWO/QHU3cgnDjqYtfLJNIPb/Ull10Dmjeco="


install:
  # The Dockerfile that defines the image that for the build environment is
  # available in this repo at devtools/centos5-build-box/Dockerfile
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull jchodera/omnia-build-box:cuda${CUDA_SHORT_VERSION}-amd30-clang38;
    fi

script:
  # Retrieve conda-build-all
  - wget -O conda-build-all --quiet https://raw.githubusercontent.com/omnia-md/conda-recipes/master/conda-build-all
  - chmod u+x conda-build-all
  # Select upload destination
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
        export UPLOAD="--upload omnia --dev --force";
    else
        export UPLOAD="--dev --force";
    fi
  - echo $UPLOAD
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then

        docker run -e UPLOAD -e BINSTAR_TOKEN -e TRAVIS_PULL_REQUEST
            -t -i --rm -v `pwd`:/io jchodera/omnia-build-box:cuda${CUDA_SHORT_VERSION}-amd30-clang38
            bash /io/devtools/docker-build.sh;

    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then

        echo "Building osx...";
        bash devtools/osx-build.sh;

    fi
