os:
  - linux
  - osx

# Supported versions: https://docs.travis-ci.com/user/languages/objective-c/#Supported-Xcode-versions
osx_image: xcode6.4

language: c
sudo: required

services:
  - docker

env:
  matrix:
    - PY_BUILD_VERSION="27"
    - PY_BUILD_VERSION="35"
    - PY_BUILD_VERSION="36"
  global:
    - CUDA_VERSION: "9.0"
    - CUDA_SHORT_VERSION: "90"
  secure: "bOeMIEmvmO4Ob+uk9kYq/4TLLq3Su2nX4byOIqUGUfkffbuvtRk777UXTQutxLYBbw9eb33/LYtC0JseyY8jIu08CPihiNih96Zo7Qyelhi3JdkwLBzuW+uFwQjU1twe2r536GAKC9wZVM+Fe8TT+OweSpYtPL93xKgJQmq6UzZKvTv+efS71JfvXC2/hZ0rWS2Grf09G66QoEbYQOo6niZWRNrqElb9aUlD24EdkK8ZvDFh5zx7ENdaNpXeaVM4MOV15cHv1v01XtvwDOp+6Bhhzc903VcMud9y7mVoiI1mSqHx3gq+JlvPEAiFwVyZkBeKrRTW2mQ3pjm6ntVESyygycLEk4rIVTzjmek/6IECrrBdNjIng4vMxUQM0vTFr5rsa5C40N9yuamIrRoUreYsVvbIU6wJCCDGRGmjZoBnufX2FG//hR/iRYA3zO7ZlRj4U/11Gp/GguAcSdc2tyOw9zf5xO80fBWzgbIDetf/SHg64tOkTFJvHr1bE9kOuUz0b/OBLasMR4CXozq7LcRAQUhq7nR57w3OLLAqVFiWrD9d4Pb9KDIi3X2GhAv0zGr6XELNDgAdvKxC+PCBtUiJWfYeEPhFF+lyW/Ti5h3azIuWuSS9IVnR8A5yx/LfDsLTDvydmvG9uhidioBhH3UplPm8WX25IAQoCe4byu4="


install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull jchodera/omnia-linux-anvil:texlive-amd30-cuda${CUDA_SHORT_VERSION};
    fi

script:
  # Retrieve conda-build-all
  - wget -O conda-build-all --quiet https://raw.githubusercontent.com/omnia-md/conda-recipes/master/conda-build-all
  - chmod u+x conda-build-all
  # Select upload destination
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
        export UPLOAD="--upload omnia --dev --force";
    else
        export UPLOAD="--dev --force";
    fi
  - echo $UPLOAD
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then

        docker run -e UPLOAD -e BINSTAR_TOKEN -e TRAVIS_PULL_REQUEST -e PY_BUILD_VERSION
            -t -i --rm -v `pwd`:/io jchodera/omnia-linux-anvil:texlive-amd30-cuda${CUDA_SHORT_VERSION}
            bash /io/devtools/docker-build.sh;

    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then

        echo "Building osx...";
        bash devtools/osx-build.sh;

    fi
