package:
  name: openmm-forcefields
  version: 0.3.0

source:
  git_url: https://github.com/choderalab/openmm-forcefields.git
  git_tag: 0.3.0

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - openmm >=7.2.0

  run:
    - python
    - openmm >=7.2.0

test:
  requires:
    - nose
    - nose-timer
  imports:
    - openmmforcefields

about:
  home: https://github.com/choderalab/openmm-forcefields
  license: MIT License
