package:
  name: openpathsampling-dev
  version: 0.0.0

source:
  git_url: https://github.com/choderalab/openpathsampling.git

build:
  preserve_egg_dir: True
  number: 0
  skip:
    - [win]
    - [py3k]

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - scipy
    - pandas
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - docopt
    - pyyaml
    - mdtraj 1.5.1
    - svgwrite
    - networkx
    - matplotlib

test:
  requires:
    - nose
    - nose-timer
    - python-coveralls
    - msmbuilder
    - pyemma
    - ipynbtest

  imports:
    - openpathsampling

about:
  home: https://github.com/choderalab/openpathsampling
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: framework for running path sampling MD simulations
