package:
  name: skorch
  version: 0.3.0a0

source:
  git_url: https://github.com/dnouri/skorch.git
  git_tag: master
  patches:
    - 0001-Compatibility.patch

extra:
  upload: dev

build:
  skip: True  # [win or osx or py27]

extra:
  maintainers:
   - cxhernandez

requirements:
  build:
    - python
    - scipy
    - numpy
    - scikit-learn
    - tabulate
    - tqdm

  run:
    - python
    - scipy
    - numpy
    - pytorch
    - scikit-learn
    - pyyaml
    - tabulate
    - tqdm

test:
  # Modify tests to get around bug (remove in future versions)
  #imports:
  #  - skorch

about:
    home: https://github.com/dnouri/skorch
    license: BSD-3
