package:
  name: openforcefield
  version: 0.2.0

source:
    git_url: https://github.com/openforcefield/openforcefield.git
    git_tag: topology

build:
  preserve_egg_dir: True
  number: 0 # Build number and string do not work together.
  #string: py{{ py }}_a1 # Alpha version 1.
  skip: True # [win or py27 or py35]

extra:
  force_upload: True
  upload: main # Upload to anaconda with the "main" label.

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - openmm
    - networkx
    - parmed
    - rdkit ==2018.09.01 # pinned because conda-forge 2018.09.03 causes segfaults on osx py37
    - ambermini
    - packaging
    # Serialization: Should these be optional?
    - toml
    - bson
    - msgpack-python
    - xmltodict
    - pyyaml

about:
  home: https://github.com/openforcefield/openforcefield
  license: MIT
  license_file: LICENSE
  description: The Open Forcefield Toolkit provides implementations of the SMIRNOFF format, parameterization engine, and other tools.
