package:
  name: openforcefield
  version: 1.0a1

source:
    git_url: https://github.com/openforcefield/openforcefield.git
    git_tag: topology

build:
  preserve_egg_dir: True
  number: 0
  #skip: True # [win]

extra:
  force_upload: True
  upload: main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.14
    - networkx >=2.0
    - lxml
    - icu 58*  # This is a lxml dependency but sometimes conda installs version 56
    - packaging
    # Should these be optional?
    - rdkit
    - ambertools
    #- parmed # uncomment when new ambermini (without parmed) is built
    # Should we require this? It's useful for tests and examples, but not strictly required
    - openmmtools # If we remove this we need to install openmm (which minimum version?)
    # Serialization: Should these be optional?
    - pyyaml
    - toml
    - bson
    - msgpack-python
    - xmltodict

test:
  requires:
    - pytest
  imports:
    - openforcefield

about:
  home: https://github.com/openforcefield/openforcefield
  license: MIT
