package:
  name: openforcefield
  version: 0.2.0

source:
    git_url: https://github.com/openforcefield/openforcefield.git
    git_tag: topology

build:
  preserve_egg_dir: True
  number: 0 # Build number and string do not work together.
  #string: py{{ py }}_a1 # Alpha version 1.
  #skip: True # [win]

extra:
  force_upload: True
  upload: main # Upload to anaconda with the "main" label.

requirements:
  build:
    - python
    - setuptools
    - pandas

  run:
    - python
    - numpy
    - networkx
    - lxml
    - icu 58*  # This is a lxml dependency but sometimes conda installs version 56
    - parmed
    - matplotlib
    - pandas
    - packaging
    # Should we require this? It's useful for tests and examples, but not strictly required
    - openmmtools
    # Serialization: Should these be optional?
    - pyyaml
    - toml
    - bson
    - msgpack-python
    - xmltodict

about:
  home: https://github.com/openforcefield/openforcefield
  license: MIT
  license_file: LICENSE
  description: The Open Forcefield Toolkit provides implementations of the SMIRNOFF format, parameterization engine, and other tools. 
